apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ehandelkanal-2
  namespace: default
  labels:
    team: integrasjon
spec:
  image: "repo.adeo.no:5443/integrasjon/ehandelkanal-2:@@VERSION@@"
  team: integrasjon
  replicas:
    min: 1
    max: 1
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  istio:
    enabled: false
  ingresses:
    - {{INGRESS_URL}}
  vault:
    enabled: true
    sidecar: true
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 768Mi
  env:
    - name: APP_VERSION
      value: "@@VERSION@@"
