ingresses: ["https://ehandelkanal-2.nais.adeo.no"]
entraid_target_url: "api://prod-gcp.bankkommunikasjon.sokos-vefasrest/.default"
vefasrest_message_url: "https://sokos-vefasrest-gcp.intern.nav.no/api/messages"
vefasrest_inbox_url: "https://sokos-vefasrest-gcp.intern.nav.no/api/inbox"
access_policy_outbound_rules:
  - application: "sokos-vefasrest"
    namespace: "bankkommunikasjon"
    cluster: "prod-gcp"