app.profile=dev

entraid.target.url=api://dev-fss.team-oebs.ehandelkanal-2/.default

vefasrest.inbox.url=https://sokos-vefasrest.intern.dev.nav.no/api/inbox/
vefasrest.messages.url=https://sokos-vefasrest.intern.dev.nav.no/api/messages/
vefasrest.outbox.url=https://sokos-vefasrest.intern.dev.nav.no/api/outbox/
vefasrest.transmit.url=https://sokos-vefasrest.intern.dev.nav.no/api/transmit/
